### PR TITLE
Add support for searching hwmon sensors by name

### LINKED ISSUE #43: Support for thermal_zone temperatures by name
Feature request:

I'm using `thermal_zone` temperatures instead of `hwmon` because the paths are more predictable and do not disappear (unlike the `temp[0-9]_input` hwmon files). Here are the paths I'm using:
```
$ cat /sys/devices/virtual/thermal/thermal_zone[0-3]/temp
43000
40500
30000
44000
```

However they might still change order, so I would like to set each sensor by the name instead of the path. Names are stored in the `type` files:
```
$ cat /sys/devices/virtual/thermal/thermal_zone[0-3]/type
acpitz
pch_skylake
iwlwifi
x86_pkg_temp
```

This way I would adjust the parameters more accurately, for example if I want to exclude a specific sensor (for example the `iwlwifi` that disappears if wifi is disabled).

### PR DESCRIPTION
**Pull request by akheron**
Add a new config directive `thermal_zone name` which searches /sys/devices/virtual/thermal for a file called `name`. It its content matches the name, use the `temp1_input` next to it as the temperature input.

Fixes #43

### CODE REVIEW

**Comment by vmatare** [comment]
Oh thanks, I like the idea, but in the current form it's not as useful as it could be. I think all hwmon sensors have this `name` file, so I'd like to see it generalized to arbitrary sysfs paths. That is, don't add a new HwmonSensor class, but extend the existing one so it is able to look up sensors by name. Haven't looked closely yet, but the code looks well-structured enough to achieve that easily.

After that I'd also like to see the functionality integrated in the YAML parser, as well, but I can also do that if you don't want to read into the YAML API ;-)

**Comment by akheron** [comment]
I'm not sure what you mean about extending the `HwmonSensor` class. Do you mean that it would be given a parent directory, and then it would search the sensor under that directory by name? Then the config syntax would be something like:
```
hwmon /sys/devices/thermal/:sensor_name (correction_value)
```

**Comment by akheron** [comment]
BTW, I need this change because it seems that my CPU temperature hwmon sensor's sysfs path changes between boots and even suspend-to-ram/resume rounds :grimacing:

**Comment by vmatare** [comment]
Yeah, so what I meant was to integrate the name-search functionality into the existing `HwmonSensorDriver` class. You have some logic for handling multiple `tempN_input` files in `yamlconfig.cpp`. Check out [thinkfan.conf.yaml](https://github.com/vmatare/thinkfan/blob/master/examples/thinkfan.conf.yaml). There you have an example for how different sub-sensors can be selected by index.

**Comment by akheron** [comment]
I force-pushed a change which discards the driver changes and does it all in the yaml side. It first recursively searches for a hwmon that has the correct name, and then feeds that hwmon to `find_hwmons()`, as you suggested.

**Comment by vmatare** [comment]
Yes, I like that much better. I also wanted to deprecate the old config syntax, which is another reason why new features such as this should go into the YAML config.

**Pull request merged**
